# Default application configuration that all configurations inherit from.

#
# For more info, see here:
# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md

scss_files: "**/*.scss"

linters:

  # Readability. Really only impacts !important.
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  # instead of "border: none;" use "border: 0;"
  BorderZero:
    enabled: true

  # Do not allow color keyworda such as "red, green, blue, etc" must use Hex or RGBa
  ColorKeyword:
    enabled: true

  # Optimization
  # SASS supports 2 types of comments those that get removed on build and those that do not.
  # This checks for any comments that will not be removed. There is rarely a case where a comment should not be removed.
  Comment:
    enabled: true

  # Optimization.
  # Checks for leftover @debug statements
  DebugStatement:
    enabled: true

    # Readbility and Functionality.
    # Rule sets should be ordered as follows:
    # @extend declarations,
    # @include declarations without inner @content,
    # properties,
    # @include declarations with inner @content,
    # then nested rule sets.
  DeclarationOrder:
    enabled: true

    # Readability, maintainability.
    # Check for duplicates properties.
  DuplicateProperty:
    enabled: true

  # Good
  # @if {
  # ...
  # }
  # @else {
  #   ...
  # }
  #
  # Bad
  # @if {
  # ...
  # } @else {
  #   ...
  # }
  ElsePlacement:
    enabled: true
    style: new_line

    # Readability.
    # Separate rule, function, and mixin declarations with empty lines.
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

    # Reports when you have an empty rule set.
    # Setting this to false since empty rules will get compiled out, and it can be helpful to leave stubs.
  EmptyRule:
    enabled: false

    # Files should always have a final newline. This results in better diffs when adding lines to the file, since SCM systems such as git won't think that you touched the last line.
  FinalNewline:
    enabled: true
    present: true

    # Use 3 digit hex values where possible.
  HexLength:
    enabled: false
    style: short # or 'long'

    #Hex should be written in lower case. Who wants to hold the shift key anyway?
  HexNotation:
    enabled: false
    style: lowercase # or 'uppercase'

    # Ensure hexadecimal colors are valid (either three or six digits).
  HexValidation:
    enabled: true

    # Avoid using ID selectors.
    # Not that in some cases this IS acceptable, but most of the time it should not be used.
    # Be sure you can defend your choice.
  IdSelector:
    enabled: true

    # The basenames of @imported SCSS partials should not begin with an underscore and should not include the filename extension.
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  # Readability. Use a single tab, not spaces for each indent level
  Indentation:
    enabled: true
    character: space # 'tab' or 'space'
    width: 4

  # Don't write leading zeros for numeric values with a decimal point.
  # GOOD  margin: 0.5em
  # BAD margin: .5em
  LeadingZero:
    enabled: true
    style: include_zero # or 'include_zero'

    # Reports when you define the same selector twice in a single sheet.
  MergeableSelector:
    enabled: true
    force_nesting: true

    # Naming conventions for Functions, mixins, and variables
    # TODO - implement regex pattern for out conventions
  NameFormat:
    enabled: false
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'hyphenated_lowercase' BEM', or a regex pattern

    # Avoid nesting selectors too deeply.
  NestingDepth:
    enabled: true
    max_depth: 3

    # Using a class selector with the @extend statement statement usually results in more generated CSS than when using a placeholder selector. Furthermore, Sass specifically introduced placeholder selectors in order to be used with @extend
  PlaceholderInExtend:
    enabled: true

    # Readanility.
    # Sort properties in alphabetical order, as it's simple and it can benefit gzip compression.
  PropertySortOrder:
    ignore_unspecified: false
    order:
        - font
        - font-family
        - font-size
        - font-weight
        - font-style
        - font-variant
        - font-size-adjust
        - font-stretch
        - font-effect
        - font-emphasize
        - font-emphasize-position
        - font-emphasize-style
        - font-smooth
        - line-height
        -
        - position
        - z-index
        - top
        - right
        - bottom
        - left
        -
        - display
        - visibility
        - float
        - clear
        - overflow
        - overflow-x
        - overflow-y
        - -ms-overflow-x
        - -ms-overflow-y
        - clip
        - zoom
        - flex-direction
        - flex-order
        - flex-pack
        - flex-align
        -
        - -webkit-box-sizing
        - -moz-box-sizing
        - box-sizing
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        -
        - table-layout
        - empty-cells
        - caption-side
        - border-spacing
        - border-collapse
        - list-style
        - list-style-position
        - list-style-type
        - list-style-image
        -
        - content
        - quotes
        - counter-reset
        - counter-increment
        - resize
        - cursor
        - -webkit-user-select
        - -moz-user-select
        - -ms-user-select
        - user-select
        - nav-index
        - nav-up
        - nav-right
        - nav-down
        - nav-left
        - -webkit-transition
        - -moz-transition
        - -ms-transition
        - -o-transition
        - transition
        - -webkit-transition-delay
        - -moz-transition-delay
        - -ms-transition-delay
        - -o-transition-delay
        - transition-delay
        - -webkit-transition-timing-function
        - -moz-transition-timing-function
        - -ms-transition-timing-function
        - -o-transition-timing-function
        - transition-timing-function
        - -webkit-transition-duration
        - -moz-transition-duration
        - -ms-transition-duration
        - -o-transition-duration
        - transition-duration
        - -webkit-transition-property
        - -moz-transition-property
        - -ms-transition-property
        - -o-transition-property
        - transition-property
        - -webkit-transform
        - -moz-transform
        - -ms-transform
        - -o-transform
        - transform
        - -webkit-transform-origin
        - -moz-transform-origin
        - -ms-transform-origin
        - -o-transform-origin
        - transform-origin
        - -webkit-animation
        - -moz-animation
        - -ms-animation
        - -o-animation
        - animation
        - -webkit-animation-name
        - -moz-animation-name
        - -ms-animation-name
        - -o-animation-name
        - animation-name
        - -webkit-animation-duration
        - -moz-animation-duration
        - -ms-animation-duration
        - -o-animation-duration
        - animation-duration
        - -webkit-animation-play-state
        - -moz-animation-play-state
        - -ms-animation-play-state
        - -o-animation-play-state
        - animation-play-state
        - -webkit-animation-timing-function
        - -moz-animation-timing-function
        - -ms-animation-timing-function
        - -o-animation-timing-function
        - animation-timing-function
        - -webkit-animation-delay
        - -moz-animation-delay
        - -ms-animation-delay
        - -o-animation-delay
        - animation-delay
        - -webkit-animation-iteration-count
        - -moz-animation-iteration-count
        - -ms-animation-iteration-count
        - -o-animation-iteration-count
        - animation-iteration-count
        - -webkit-animation-direction
        - -moz-animation-direction
        - -ms-animation-direction
        - -o-animation-direction
        - animation-direction
        - text-align
        - -webkit-text-align-last
        - -moz-text-align-last
        - -ms-text-align-last
        - text-align-last
        - vertical-align
        - white-space
        - text-decoration
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-style
        - text-emphasis-position
        - text-indent
        - -ms-text-justify
        - text-justify
        - letter-spacing
        - word-spacing
        - -ms-writing-mode
        - text-outline
        - text-transform
        - text-wrap
        - text-overflow
        - -ms-text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - -ms-word-wrap
        - word-wrap
        - word-break
        - -ms-word-break
        - -moz-tab-size
        - -o-tab-size
        - tab-size
        - -webkit-hyphens
        - -moz-hyphens
        - hyphens
        - pointer-events
        -
        - opacity
        - filter:progid:DXImageTransform.Microsoft.Alpha(Opacity
        - -ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha
        - -ms-interpolation-mode
        - color
        - border
        - border-width
        - border-style
        - border-color
        - border-top
        - border-top-width
        - border-top-style
        - border-top-color
        - border-right
        - border-right-width
        - border-right-style
        - border-right-color
        - border-bottom
        - border-bottom-width
        - border-bottom-style
        - border-bottom-color
        - border-left
        - border-left-width
        - border-left-style
        - border-left-color
        - -webkit-border-radius
        - -moz-border-radius
        - border-radius
        - -webkit-border-top-left-radius
        - -moz-border-radius-topleft
        - border-top-left-radius
        - -webkit-border-top-right-radius
        - -moz-border-radius-topright
        - border-top-right-radius
        - -webkit-border-bottom-right-radius
        - -moz-border-radius-bottomright
        - border-bottom-right-radius
        - -webkit-border-bottom-left-radius
        - -moz-border-radius-bottomleft
        - border-bottom-left-radius
        - -webkit-border-image
        - -moz-border-image
        - -o-border-image
        - border-image
        - -webkit-border-image-source
        - -moz-border-image-source
        - -o-border-image-source
        - border-image-source
        - -webkit-border-image-slice
        - -moz-border-image-slice
        - -o-border-image-slice
        - border-image-slice
        - -webkit-border-image-width
        - -moz-border-image-width
        - -o-border-image-width
        - border-image-width
        - -webkit-border-image-outset
        - -moz-border-image-outset
        - -o-border-image-outset
        - border-image-outset
        - -webkit-border-image-repeat
        - -moz-border-image-repeat
        - -o-border-image-repeat
        - border-image-repeat
        - outline
        - outline-width
        - outline-style
        - outline-color
        - outline-offset
        - background
        - filter:progid:DXImageTransform.Microsoft.AlphaImageLoader
        - background-color
        - background-image
        - background-repeat
        - background-attachment
        - background-position
        - background-position-x
        - -ms-background-position-x
        - background-position-y
        - -ms-background-position-y
        - -webkit-background-clip
        - -moz-background-clip
        - background-clip
        - background-origin
        - -webkit-background-size
        - -moz-background-size
        - -o-background-size
        - background-size
        - box-decoration-break
        - -webkit-box-shadow
        - -moz-box-shadow
        - box-shadow
        - filter:progid:DXImageTransform.Microsoft.gradient
        - -ms-filter:\\'progid:DXImageTransform.Microsoft.gradient
        - text-shadow
    separate_groups: false

    # Reports when you use an unknown CSS property (ignoring vendor-prefixed properties).
  PropertySpelling:
    enabled: true
    extra_properties: []

    # Maintability
    # Avoid qualifying elements in selectors (also known as "tag-qualifying").
    # Don't use standard HTML tags as selectors. Only uses classes and psuedo-classes
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false

    # Don't write selectors with a depth of applicability greater than X.
  SelectorDepth:
    enabled: true
    max_depth: 3

    #Enforce BEM naming style
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM #'hyphenated_lowercase'  or 'BEM', or 'snake_case', or 'camel_case', or a regex pattern

    #Prefer the shortest shorthand form possible for properties that support it.
    # BAD margin: 1px 1px 1px 1px;
    # GOOD margin: 1px;
  Shorthand:
    enabled: true

  # Properties within rule sets should each reside on their own line.
  # Readability. File size is not an issue since everything will get compressed anyway.
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  # Readability
  # Split selectors onto separate lines after each comma.
  SingleLinePerSelector:
    enabled: true

  # Readability
  # Commas in lists should be followed by a space.
  SpaceAfterComma:
    enabled: true

  # Readability
  # Properties should be formatted with a single space separating the colon from the property's value.
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

    # Reradability
    # Properties should be formatted with no space between the name and the colon.
  SpaceAfterPropertyName:
    enabled: true

    # Readability
    # Opening braces should be preceded by a single space.
  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

    # Readability
    # Parentheses should not be padded with spaces.
  SpaceBetweenParens:
    enabled: true
    spaces: 0

    # String literals should be written with single quotes unless using double quotes would save on escape characters.
  StringQuotes:
    enabled: true
    style: double_quotes # or double_quotes

    # Property values; @extend, @include, and @import directives; and variable declarations should always end with a semicolon.
  TrailingSemicolon:
    enabled: true

    # Don't write trailing zeros for numeric values with a decimal point.
  TrailingZero:
    enabled: false

    # Numeric values should not contain unnecessary fractional portions.
  UnnecessaryMantissa:
    enabled: true

  # Do not use parent selector references (&) when they would otherwise be unnecessary.
  UnnecessaryParentReference:
    enabled: true

    # URLs should not contain protocols or domain names.
  UrlFormat:
    enabled: false

    # URLs should always be enclosed within quotes.
  UrlQuotes:
    enabled: true

    # Avoid vendor prefixes. That is, don't write them yourself.
    # The toolkit should add these for you, if not let the Front End team know ASAP so it can be fixed.
  VendorPrefixes:
    enabled: true
    identifier_list: base
    include: []
    exclude: []

    # Omit length units on zero values.
  ZeroUnit:
    enabled: true

    # Omit all lint checks for anything related to the Compass library which we do not use
  Compass::*:
    enabled: false
